### ISSUE TITLE
[eWeLink] WebSocket was closed. Reason [1006]

### ISSUE THREAD

**Issue by P1xellat3d** [gbro115/homebridge-ewelink#16]
Hey guys,

This seems to have just started happening recently.

Whenever Homebridge is sending a command to eWeLink devices, the request seems to always timeout. Below is what the log reads and it keeps repeating on and on without resolve:

```
[2018-4-18 08:19:52] [eWeLink] Setting power state to [on] for device [Hall and Porch CH 1]

WebSocketClient: error { '0':

   { Error: getaddrinfo ENOTFOUND us-long.coolkit.cc us-long.coolkit.cc:8080

    at errnoException (dns.js:50:10)

    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

     code: 'ENOTFOUND',

     errno: 'ENOTFOUND',

     syscall: 'getaddrinfo',

     hostname: 'us-long.coolkit.cc',

     host: 'us-long.coolkit.cc',

     port: '8080' } }

[2018-4-18 08:20:10] [eWeLink] WebSocket was closed. Reason [1006]

WebSocketClient: reconnecting...
```

My suspicion is that the individual Sonoff devices aren't connected to the internet (perhaps a Wi-Fi issue?) which is leading to this message.

If anyone has any insights on how to fix this, that would be greatly appreciated!

**Comment by P1xellat3d** [comment]
Tagging @MrTomAsh for visibility :)

**Comment by P1xellat3d** [comment]
Also like to point out that it doesn't seem to be an Auth-token/Header issue, since it seems to have picked up my device name just fine (i.e. **Hall and Porch CH 1)**

**Comment by ek32** [comment]
I have the same problem with Sonoff Basic.
It seems that the webservice server is changed

**Comment by Stuart-Richards** [comment]
I'm seeing the same issue too.

**Comment by Joni-Pekka** [comment]
Same problem as discussed in this other topic: https://github.com/gbro115/homebridge-ewelink/issues/17
The problem isn't with the switches, because mine work with eWeLink-software. I suspect that the three chinese notifications on eWeLink iOS-app that were sent this morning had something to do with this.

**Comment by P1xellat3d** [comment]
Does anyone have any screenshots of these notifications? I can read and speak Chinese so I may be able to help decipher if there is any relevance.

**Comment by FlyingKiwiJosh** [comment]
Hi. I’m having a similar issue. I updated the server as per the other issue people were having. My eWeLink app still works and it is the correct auth token so not sure why it won’t work. 

[2018-4-22 04:00:42] [eWeLink] WebSocket was closed. Reason [1006]
WebSocketClient: retry in 5000ms 1006
[2018-4-22 03:58:02] [eWeLink] WebSocket messge received:  {"error":0,"apikey":"83df1414-1be9-4d70-aefb-8e2039a852af","config":{"hb":1,"hbInterval":145},"sequence":"1524333482153"}
[2018-4-22 03:58:02] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"152433348215300","apkVesrion":"1.8","os":"ios","at":"removed auth key","apikey":"83df1414-1be9-4d70-aefb-8e2039a852af","ts":"1524333482","model":"iPhone10,6","romVersion":"11.1.2","sequence":1524333482153}]

**Comment by MrTomAsh** [comment]
Please try to update your config.json file as follow:
`
"webSocketApi" : "eu-pconnect3.coolkit.cc"
`

**Comment by jwhits** [comment]
Using the US version worked for me too.
`us-pconnect3.coolkit.cc`

**Comment by P1xellat3d** [comment]
Thanks @MrTomAsh and @jwhits! 

Using `us-pconnect3.coolkit.cc` worked for me also.

**Comment by cecildaniel2003** [comment]
I am getting the same error but using the Asia version - "as-api.coolkit.cc:8080" as the apiHost, any idea what would the webSocketApi would be ?

**Comment by cecildaniel2003** [comment]
> I am getting the same error but using the Asia version - "as-api.coolkit.cc:8080" as the apiHost, any idea what would the webSocketApi would be ?

How stupid I found this to be working : as-pconnect3.coolkit.cc

**Comment by deng-san** [comment]
Hi, Please help me.
I have got the error "WebSocket was closed. Reason[1006].
below is my config.json setting. What is the issue?
  {
            "platform": "eWeLink",
            "name": "太郎",
            "countryCode": "81",
            "email": " XXXXXXXXX@XXXXXXX.com",
            "password": "************",
            "imei": "C91CDC73-EC7B-4AC8-B5BA-9B084CE48411"
        }

**Comment by bwp91** [comment]
@deng-san 
your config is for homebridge-ewelink-max, this plugin is homebridge-ewelink that’s why it isn’t working

**Comment by deng-san** [comment]
Hi,Ben

thank you for your mail.

I have settled the issue.

best regards

Z. S. Deng

**Comment by markkibble** [comment]
> Please try to update your config.json file as follow:
> `"webSocketApi" : "eu-pconnect3.coolkit.cc"`

Hi Tom,  I'm new to programming and trying to get my Sonoff kit to work.  When you state 'add this ("webSocketApi" : "eu-pconnect3.coolkit.cc") to the config file'. does it matter where I add it?    I can't get it to work, I'm in UK so tried eu and us variants but no dice.  Can you help at all?

**Comment by markkibble** [comment]
In fact can anyone help please?  The sonoffs are recognised in Homebridge and on my iPhone in Apple Home but I can't control them from either.  They all work fine using ewe link..

Config is:


{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "0E:73:32:47:82:36",
        "port": 51839,
        "pin": "472-76-xxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "eWeLink",
            "countryCode": 44,
            "email": "xxxx.com",
            "password": "xxxxx",
            "imei": "xxxxxxxxxxxxxxxxxxxxx",
            "groups": [
                {
                    "type": "blind",
                    "handle_api_changes": true
                }
            ],
            "webSocketApi": "us-pconnect3.coolkit.cc",
            "platform": "eWeLink"
        }
    ]
}

**Comment by bwp91** [comment]
@markkibble 
The plugin has had a lot of updates since, and some of the configuration options you have added are not necessary.
Please refer to 
https://github.com/bwp91/homebridge-ewelink/wiki/Configuration
for the most up to date configuration fields.
Thanks

**Comment by markkibble** [comment]
Ben

 

Thanks so much for this!  I uninstalled the older version I had and installed homebridge-ewelink v3.18.1

 

It all works fine now (so far).  I have lost the ‘Accessories’ tab in Homebridge webpage but otherwise it works from my iphone with Apple Home. 

 

Plan to now have a stab at integrating my Arduino next – I think I need to add a homebridge http plugin – 

 

I’m new to all this webby stuff, I’m a retired electrical engineer and having a stab at home automation for my place - so really appreciate your advice as I learn.

 

I do a lot of amateur theatre lighting controlled with DMX and have got loads of old dimmers and switches that control bits of my house – so working towards linking all that into the project. eBay is full of all this high-end kit which gets ripped out of nightclubs and pubs when they are refurbished and they are just waiting to be repurposed! Much better to control things properly via hardwired OEM kit than dodgey little relays and wifi if possible!

 

Thanks again for the link and help

 

Mark. (Oxford UK)
