### ISSUE TITLE
Error on startup Homebridge eWeLink 'Error: unexpected server response (200)'

### ISSUE THREAD

**Issue by stehof2** [gbro115/homebridge-ewelink#26]
Hi,

I will explain shortly what the situation is, I installed the app Homebridge from Github on my Raspberry: https://github.com/nfarina/homebridge

Installation was successful, so, so far so good. But then I installed the plugin eWeLink for the Homebridge app: https://github.com/gbro115/homebridge-ewelink the installation went good as well, but when I try to start the application now, it gives the following output:

> [2018-6-1 12:38:46] [eWeLink] A total of [0] accessories were loaded from the local cache
> [2018-6-1 12:38:46] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-ota.coolkit.cc:8080]
> [2018-6-1 12:38:46] Homebridge is running on port 51826.
> [2018-6-1 12:38:46] [eWeLink] eWeLink HTTPS API reports that there are a total of [108] devices registered
> [2018-6-1 12:38:46] [eWeLink] Evaluating if devices need to be removed...
> [2018-6-1 12:38:46] [eWeLink] Evaluating if new devices need to be added...
> [2018-6-1 12:38:46] [eWeLink] Device [undefined], ID : [undefined] will be added
> [2018-6-1 12:38:46] [eWeLink] A device with an unknown type was returned. It will be skipped. undefined
> [2018-6-1 12:38:46] [eWeLink] API key retrieved from web service is [undefined]
> [2018-6-1 12:38:46] [eWeLink] Connecting to the WebSocket API at [wss://eu-api.coolkit.cc:8080/api/ws]
> WebSocketClient: error { '0': Error: unexpected server response (200)
>     at ClientRequest._req.on (/usr/lib/node_modules/homebridge-ewelink/node_modules/ws/lib/WebSocket.js:653:21)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
>     at TLSSocket.socketOnData (_http_client.js:440:20)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11) }
> WebSocketClient: retry in 5000ms 1006
> [2018-6-1 12:38:46] [eWeLink] WebSocket was closed. Reason [1006]

Who can help me solve this?

**Comment by 4Xsample** [comment]
I have some problem like this.

[2018-6-8 23:59:55] [eWeLink] API key retrieved from web service is [d084fb4a-****-****-****-453ee0838731]
[2018-6-8 23:59:55] [eWeLink] Connecting to the WebSocket API at [wss://eu-ota.coolkit.cc:8080/api/ws]
WebSocketClient: error { '0': Error: unexpected server response (404)
    at ClientRequest._req.on (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) }
WebSocketClient: retry in 5000ms 1006

I can't figure out how to solve it.

**Comment by stehof2** [comment]
Apparently you read the manual the same I did, but we should contact a different websocket server, I use this in my config.json now and that’s working for me ;-)

```
		"apiHost": "eu-api.coolkit.cc:8080",
		"webSocketApi": "eu-pconnect3.coolkit.cc"
```

**Comment by stehof2** [comment]
Issue can be closed, see solution above!

**Comment by skycrack-77** [comment]
"pip3 install zeroconf" is needed
and i change to the EU Server in File ewelink_client.py

155: self.apiHost = 'eu-api.coolkit.cc:8080'
156: self.webSocketApi = 'eu-pconnect3.coolkit.cc'
works fine.
Thanks for the amazing work on this App.
