### ISSUE TITLE
Login to ewelink

### ISSUE THREAD

**Issue by cis2131** [gbro115/homebridge-ewelink#3]
I have testet your great plugin, and it works fine.

Would it be possible to make your plugin do the login to https://api.coolkit.cc:8080. ?

I know that it will log the app out, but i rather use homekit than the app.. And if i need it, i can just login again.
Another workaround could be to create another account, and share the buttons to that, and use this account for the plugin.

**Comment by gbro115** [comment]
I did try this out while I was putting this plugin together & was able to get it to do what you request.

I'm a bit stretched at the moment & am not going to be adding much to this project in the foreseeable future.

Nonetheless, I will take this suggestion into consideration for a future update.

George
