### ISSUE TITLE
Support for iFan02

### ISSUE THREAD

**Issue by logname** [gbro115/homebridge-ewelink#37]
I can get a single switch for iFan02 to show up in HomeKit, but shows unresponsive.
Really hoping for at least control of levels 1,2 and 3, if not the "Smart" function also which I believe is similar to breeze where the fan pulse up and down. Don't care if the light cannot be accessed.

If there's additional info I can provide that will help add support, please ask.

**Comment by logname** [comment]
I now know how to do this. It's weird, but works. Probably has to update the persists file in homebridge and that's why it doesn't appear at first.

Using this index.js file

https://raw.githubusercontent.com/MrTomAsh/homebridge-ewelink/master/index.js

Change the following which occurs 3 times in the index.js file, so be sure you've changed all 3 occurrences

                                case 'PSF-B04-GL' :
                                switchesAmount = 2;
                                break;
                                case 'PSB-B04-GL' :
                                switchesAmount = 2;
                                break;
                                case 'PSF-A04-GL' :
                                switchesAmount = 4;
                                break;

to

                                case 'PSF-B04-GL' :
                                switchesAmount = 4;
                                break;
                            //  case 'PSB-B04-GL' :
                            //  switchesAmount = 2;
                            //  break;
                            //  case 'PSF-A04-GL' :
                            //  switchesAmount = 4;
                            //  break;

Now start Homebridge. It will give an error, and that's OK.

Now edit the Index.js file again to this, again making sure you've changed all 3 occurrences

                                case 'PSF-B04-GL' :
                                switchesAmount = 2;
                                break;
                            //  case 'PSB-B04-GL' :
                            //  switchesAmount = 2;
                            //  break;
                            //  case 'PSF-A04-GL' :
                            //  switchesAmount = 4;
                            //  break;

Now start homebridge again and it shouldn't give an error. No under default room in HomeKit, you'll have 5 buttons. One will remain unresponsive, no matter what. At least I do.

Step 1. One of the buttons in HomeKit under Default Room will be the light and will be labelled as CH 1 in the HomeKit. Change its name in HomeKit to "Fan Light"
Step 2. Another button in Default Room will be labelled as CH 2 in the HomeKit. Change it's name to "Fan ON" or "Level 1"
Step 3. Another one of the buttons will be named CH 3, when this button is tapped by itself, it does nothing, but when you tap "Fan ON" or "Level 1" at the same time, you will get Fan level 2 and you can confirm this by watching the EWeLink app change.
Step 4. Finally, the last button labelled CH 4 is for level 3 and acts the same as the level 2 button, in that you must have both it and the Level 1 button enabled at the same time to get level 3

To get Smart to turn on, you simple turn on all three of the level button. What very nice about this is you can simple create a HomeKit automation to turn the fan on to any level or combination of fan level and light that you want.

**Comment by Rantaholic** [comment]
Thanks for figuring this out. 
What plugin are you using in homebridge? Can you give an example of the config.json entry you’re using for it?
Thanks

**Comment by logname** [comment]
It's no different than the sample [see below]. You just need to get the Charles app for the authentication token. However, I never installed the iFan02 in my ceiling fans. I ended up using two of the iFan02 controllers for Halloween props and then put them away for the year. They're not robustly made, and not certified for use in the US or Canada. I'm now using a Lutron Caséta Fan controller instead. Much nicer and much safer. Certified in both countries.

If you want to still use them, the way I controlled them for the Halloween props was with Hubitat Elevation and Google Assistant Relay. Hubitat can send silent messages via Google Assistant Relay to the EWeLink app, officially. No need to hack anything. Yes it's cloud, but it was only about a 1 second delay. Perfectly acceptable. Only downside is it leaves your fan control open to cloud failure. The Caséta Fan control gives you piece of mind, local control, physical wall switch, pico compatibility, and HomeKit support. You need their bridge, but it's worth it. Especially if you pair it with Hubitat (which uses the Caséta Smart Bridge Pro for Telnet communication between the hub and the bridge.

{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "123-45-678"
    },
    
    "description": "Your description here",

    "accessories": [
    ],

    "platforms": [
        {
        "platform" : "eWeLink",
        "name" : "eWeLink",
        "authenticationToken" : "obtain-with-Charles",
        "apiHost" : "us-api.coolkit.cc:8080",
        "webSocketApi" : "us-long.coolkit.cc"
        }
    ]
}
