### ISSUE TITLE
Forked. Automatic login doesn't work.

### ISSUE THREAD

**Issue by TommyCardello** [gbro115/homebridge-ewelink#48]
Hi, @howanghk,

There is no option to create an issue specifically on your fork.

Please Go to the Settings page of your fork.
Check the box next to Issues.

Login on your fork doesn't work for me. I don't have phone number with this account. Just an email.
`[eWeLink] WebSocket messge received:  {"error":0,"apikey":"d90f485d-7015-4fb5-a814-195338a9bd03","config":{"hb":1,"hbInterval":145},"sequence":"1545808475935","socketid":"025f1ffffeb44eea-0000055d-0124dcbc-57655f1c5264569a-0cb80ec8"}`

**Comment by TommyCardello** [comment]
Okay, suddenly it started to work.
But still throws this issue.

And also this, `[eWeLink] WebSocket messge received:  {"action":"update","deviceid":"10003e6909","apikey":"d90f485d-7015-4fb5-a814-195338a9bd03","userAgent":"device","ts":0,"params":{"rssi":-68},"from":"device"}
`

**Comment by howanghk** [comment]
Hi @TommyCardello, the web socket message you posted is absolutely normal. It is not an "issue" but part of normal communication.

**Comment by TommyCardello** [comment]
Thanks. Yes, it seems to work.
It just didn't work for the first 30 minutes and then just magically started to work.
